[package]
name = "mail2json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mail-parser = "0.4.3"
serde_json = "1.0.74"
structopt = "0.3.25"
