[package]
name = "mail2json-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0.18"
clap_derive = "4.0.18"
mail-parser = { version = "0.7.0", features = ["serde_support"] }
serde_json = "1.0.87"
